//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLigaSur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_vocalia
    {
        public int id_vocalia { get; set; }
        public Nullable<int> id_partido_jugador { get; set; }
        public Nullable<int> id_equipo_partido { get; set; }
        public Nullable<int> id_partido_vocal { get; set; }
        public Nullable<int> id_partido_arbitro { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> gol_local { get; set; }
        public Nullable<int> gol_visita { get; set; }
    
        public virtual Partido_Arbitro Partido_Arbitro { get; set; }
        public virtual Partido_Equipo Partido_Equipo { get; set; }
        public virtual Partido_Jugador Partido_Jugador { get; set; }
        public virtual Partido_Vocal Partido_Vocal { get; set; }
    }
}
