//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLigaSur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partido_Vocal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partido_Vocal()
        {
            this.Detalle_vocalia = new HashSet<Detalle_vocalia>();
        }
    
        public int id_part_vocal { get; set; }
        public int id_partido { get; set; }
        public int id_vocal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_vocalia> Detalle_vocalia { get; set; }
        public virtual Partido Partido { get; set; }
        public virtual Vocal Vocal { get; set; }
    }
}
